In [1]:
import pandas as pd
import numpy as np
from numpy import argmax
from numpy import array
import warnings
warnings.filterwarnings("ignore")
import pickle

In [2]:
df = pd.read_csv(r"Desktop\heart_data.csv")

In [3]:
df = np.array(df)

In [5]:
x = df[:, 1:-1]
y = df[:, -1]
y = y.astype('int')
x = x.astype('int')
print(x,y)

[[ 50   2 168 ...   0   0   1]
 [ 55   1 156 ...   0   0   1]
 [ 52   1 165 ...   0   0   0]
 ...
 [ 52   2 183 ...   0   1   0]
 [ 61   1 163 ...   0   0   0]
 [ 56   1 170 ...   0   0   1]] [0 1 1 ... 1 1 0]


In [6]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y = train_test_split(x,y, test_size=0.3, random_state = 1)

In [7]:
from sklearn.ensemble import RandomForestClassifier

In [8]:
clf = RandomForestClassifier(n_estimators=100, max_depth=15)

In [9]:
clf.fit(train_x,train_y)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=15, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [10]:
inputt=[int(x) for x in "58 2 165 87 120 70 2 3 1 0 0".split(' ')]
final=[np.array(inputt)]

b = clf.predict_proba(final)

In [11]:
pickle.dump(clf,open('model.pkl','wb'))
model=pickle.load(open('model.pkl','rb'))